Api/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('ChatAPI/<str:id>', ChatAPI.as_view(),name="ChatAPI"),

]

Home/urls.py
from django.urls import path
from .views import *


urlpatterns=[
    path('', home2, name='home2'),
    path('home', home, name='home'),
    path('about', About, name='About'),
    path('test', test, name='test'),
    path('test_another', test_another, name='test_another'),

    path('Dashboard', Dashboard, name='Dashboard'),
    path('Login', Login, name='Login'),
    path('Logout', Logout, name='Logout'),
    path('send_simple_message', send_simple_message, name='send_simple_message'),
    path('verify/<action_id>', verify, name='verify'),
    path('Recover/<action_id>', Recover, name='Recover'),
    path('Services', Services, name='Services'),
    path('Registration', Registration, name='Registration'),
    path('Profile', Profile, name='Profile'),
    path('Profile_Pic_Edit/<action_id>', Profile_Pic_Edit, name='Profile_Pic_Edit'),
    path('Profile_Info_Edit/<action_id>', Profile_Info_Edit, name='Profile_Info_Edit'),

]

chatbot/urls.py
from django.urls import path
from .views import *


urlpatterns=[

    path('faq', faq, name='faq'),
    path('test', Test, name='Test'),
    path('chat/<action_id>', chat,name='chat'),
    path('update/<pk>', update,name='update'),
    path('delete/<pk>', delete,name='delete'),

]

myuniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Home.urls', 'Home'), namespace='Home')),
    path('Admin/', include(('Admin.urls', 'Admin'), namespace='Admin')),
    path('roomchat/', include(('roomchat.urls', 'roomchat'), namespace='roomchat')),
    path('chatbot/', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
    path('generate/', include(('GenQR.urls', 'GenQR'), namespace='GenQR')),
    path('api/', include(('Api.urls', 'Api'), namespace='Api')),
    path('imgtopdf/', include(('ImgtoPdf.urls', 'ImgtoPdf'), namespace='ImgtoPdf')),
    path('getpayment/', include(('payment.urls', 'payment'), namespace='payment')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import *


urlpatterns=[

    path('pay', getapi_withpay, name='getapi_withpay'),
    path('payadvance', getapi_advance, name='getapi_advance'),
    path('paypro', getapi_pro, name='getapi_pro'),
    path('trial', getapi_trial, name='getapi_trial'),
    path('paymentt', paymentt, name='paymentt'),
    path('ssl', ssl, name='ssl'),
    path('success', success, name='success'),
    path('fail', fail, name='fail'),
    path('get_Api', get_Api, name='get_Api'),

]

chatbot/models.py
from django.db import models

# Create your models here.



class FAQ(models.Model):
    Idd = models.CharField(blank=True, max_length=500, null=True)
    qs1 = models.CharField(blank=True, max_length=500, null=True)
    qs2 = models.CharField(blank=True, max_length=500, null=True)
    qs3 = models.CharField(blank=True, max_length=500, null=True)
    qs4 = models.CharField(blank=True, max_length=500, null=True)
    qs5 = models.CharField(blank=True, max_length=500, null=True)



    ans1 = models.CharField(blank=True, max_length=500, null=True)
    ans2 = models.CharField(blank=True, max_length=500, null=True)
    ans3 = models.CharField(blank=True, max_length=500, null=True)
    ans4 = models.CharField(blank=True, max_length=500, null=True)
    ans5 = models.CharField(blank=True, max_length=500, null=True)





class ChatFaq(models.Model):
    Idd = models.CharField(blank=True, max_length=500, null=True)
    Question = models.CharField(blank=True, max_length=1000, null=True)
    Answer = models.CharField(blank=True, max_length=1000, null=True)
    Dictionary = models.CharField(blank=True, max_length=1000, null=True)

class Trial(models.Model):
    Idd = models.CharField(blank=True, max_length=500, null=True,unique=True)
    Status = models.CharField(blank=True, max_length=1000, null=True)
    datee = models.DateField()

chatbot/forms.py
from django import forms

class FaqForm(forms.Form):
    """
    Form for individual user links
    """
    question = forms.CharField(
                    max_length=100,
                    widget=forms.TextInput(attrs={
                        'placeholder': 'question',
                    }),
                    required=False)
    answer = forms.URLField(
                    widget=forms.TextInput(attrs={
                        'placeholder': 'answer',
                    }),
                    required=False)

chatbot/views.py
from django.shortcuts import render, redirect,HttpResponse
import pandas as pd
from fuzzywuzzy import fuzz
from Home.views import *
from .models import *
import json,ast
import re
from Api.dataset_function import chatbot

import random
# Create your views here.

def Test(request):
    if request.method == "GET":

        return render(request, 'chatbot/test.html',)
    if request.method == "POST":

        ar_keys = []
        ar_values = []

        new_qs = []
        new_ans = []

        new_qs_data = []
        new_ans_data = []

        data = request.POST

        for i,j in data.items():
            ar_keys.append(i)
            ar_values.append(j)

        for k in range(1,len(ar_keys),2):
            new_qs.append(ar_keys[k])
            new_qs_data.append(ar_values[k])


        for k in range(2,len(ar_keys),2):
            new_ans.append(ar_keys[k])
            new_ans_data.append(ar_values[k])


        print(new_qs_data)
        print(new_ans_data)



        return HttpResponse('Ok')




def faq(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    if request.method == "GET":

        if ChatFaq.objects.filter(Idd=request.session['UserID']):
            pk = encode(request.session['UserID'])
            return redirect('chatbot:update',pk)

        name = reg.objects.get(ID = request.session['UserID'])
        context = {
            'name' : name
        }

        return render(request, 'chatbot/bot.html',context)

    if request.method=="POST":

        # qs1 = request.POST['qs1']
        # qs2 = request.POST['qs2']
        # qs3 = request.POST['qs3']
        # qs4 = request.POST['qs4']
        # qs5 = request.POST['qs5']
        #
        #
        # ans1 = request.POST['ans1']
        # ans2 = request.POST['ans2']
        # ans3 = request.POST['ans3']
        # ans4 = request.POST['ans4']
        # ans5 = request.POST['ans5']




        ar_keys = []
        ar_values = []

        new_qs = []
        new_ans = []

        new_qs_data = []
        new_ans_data = []

        data = request.POST


        data = data.dict()




        for i,j in data.items():
            ar_keys.append(i)
            ar_values.append(j)

        for k in range(1,len(ar_keys),2):
            new_qs.append(ar_keys[k])
            new_qs_data.append(ar_values[k])

        for k in range(2,len(ar_keys),2):
            new_ans.append(ar_keys[k])
            new_ans_data.append(ar_values[k])

        del data["csrfmiddlewaretoken"]

        # FAQ.objects.create(Idd = request.session['UserID'],qs1=qs1,qs2 = qs2, qs3 = qs3, qs4 = qs4, qs5 = qs5 , ans1 = ans1 , ans2 = ans2 , ans3 = ans3, ans4 = ans4, ans5 = ans5)

        ChatFaq.objects.create(Idd = request.session['UserID'],Question = new_qs_data ,Answer = new_ans_data, Dictionary = data)
        code = encode(request.session['UserID'])
        context = {
            'code' : code
        }
        return render(request,'chatbot/code.html',context)


def chat(request,action_id):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    df = pd.DataFrame()
    if request.method == "GET":

        return render(request, 'chatbot/chat_msg.html')

    if request.method=="POST":

        try:

            pk = decode(action_id)

            if ChatFaq.objects.filter(Idd = pk).first():

                msg = request.POST['msg']

                user = ChatFaq.objects.filter(Idd = pk).first()
                user_type = reg.objects.filter(ID=pk).first()

                # QS = [user.qs1,user.qs2,user.qs3,user.qs4,user.qs5]
                # ANS = [user.ans1,user.ans2,user.ans3,user.ans4,user.ans5]

                ini_list1 = user.Question
                ini_list2 = user.Answer


                res1 = ini_list1.strip('][').split(', ')
                res2 = ini_list2.strip('][').split(', ')

                print(res1)
                print(res2)


                df['Question'] = res1
                df['Answer'] = res2


                for i in range(len(df)):


                    f = fuzz.token_sort_ratio(msg, df['Question'][i])

                    if f >= 80.0:
                        # remove commas from end
                        val = df['Answer'][i].rstrip("\'")
                        # remove commas from start
                        val = val.lstrip("\'")
                        context = {
                            'idd' : pk,
                            'msg1': msg,
                            'msg' : val
                        }
                        return render(request,'chatbot/chat_msg.html',context)
                    else:
                        continue

                context = {
                    'idd': pk,
                    'msg1' : msg,
                    'msg' : chatbot(user_type.type,msg)

                }
                return render(request, 'chatbot/chat_msg.html', context)
            else:
                return HttpResponse("Chatbot not available")
        except:
            return HttpResponse("Chatbot is not valid format")


def update(request,pk):


    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    pk = decode(pk)
    if request.method == "GET":
        user = ChatFaq.objects.get(Idd=pk)

        data = user.Dictionary

        data = ast.literal_eval(data)

        print(data)

        ar_keys = []
        ar_values = []

        new_qs = []
        new_ans = []

        new_qs_data = []
        new_ans_data = []

        num = []


        for i,j in data.items():
            ar_keys.append(i)
            ar_values.append(j)

        for k in range(0,len(ar_keys),2):
            new_qs.append(ar_keys[k])
            new_qs_data.append(ar_values[k])


        for k in range(1,len(ar_keys),2):
            new_ans.append(ar_keys[k])
            new_ans_data.append(ar_values[k])

        pk = encode(pk)

        print(ar_keys)
        print(ar_values)

        print(new_qs)
        print(new_ans)

        user = zip(new_qs_data,new_ans_data)
        context = {
            'user': user,
            'user_api' : pk,
            'name' : request.session['UserName'],
        }
        return render(request, 'chatbot/update.html',context)

    if request.method == "POST":
        # qs1 = request.POST['qs1']
        # qs2 = request.POST['qs2']
        # qs3 = request.POST['qs3']
        # qs4 = request.POST['qs4']
        # qs5 = request.POST['qs5']
        #
        # ans1 = request.POST['ans1']
        # ans2 = request.POST['ans2']
        # ans3 = request.POST['ans3']
        # ans4 = request.POST['ans4']
        # ans5 = request.POST['ans5']



        # user = ChatFaq.objects.filter(Idd=pk)

        # for i in user:
        #     i.qs1 = qs1
        #     i.qs2 = qs2
        #     i.qs3 = qs3
        #     i.qs4 = qs4
        #     i.qs5 = qs5
        #
        #
        #     i.ans1 = ans1
        #     i.ans2 = ans2
        #     i.ans3 = ans3
        #     i.ans4 = ans4
        #     i.ans5 = ans5
        #
        #     i.save()


        user = ChatFaq.objects.get(Idd=pk)


        ar_keys = []
        ar_values = []

        new_qs = []
        new_ans = []

        new_qs_data = []
        new_ans_data = []

        data = request.POST
        data = data.dict()



        print(data)

        for i,j in data.items():

            print("key", i)
            print("val", j)

            ar_keys.append(i)
            ar_values.append(j)

        for k in range(1,len(ar_keys),2):
            new_qs.append(ar_keys[k])
            new_qs_data.append(ar_values[k])


        for k in range(2,len(ar_keys),2):
            new_ans.append(ar_keys[k])
            new_ans_data.append(ar_values[k])

        del data["csrfmiddlewaretoken"]

        print(ar_keys)
        print(ar_values)

        print(new_qs)
        print(new_ans)

        user.Question = new_qs_data
        user.Answer = new_ans_data
        user.Dictionary = data
        user.save()

        code = encode(pk)
        context = {
            'code': code
        }
        return render(request, 'chatbot/code.html', context)

def delete(request,pk):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    pk = decode(pk)
    user = ChatFaq.objects.get(Idd = pk)
    user.delete()
    return redirect('chatbot:faq')

templates/chatbot/bot.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}

    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1></h1>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .page-header -->

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="donation-form-wrap">
                    <h2>Hi {{name.Name}}!</h2>

                    <h4 class="mt-5">Create Your Own Chatbot</h4>
                    <br>
                    <h5><i style="color:blue">Note: </i> This Chatbot will create based on your "Company Type". You can change your "Company Type" from your <a style="text-decoration: none; color:blue;" href="{% url 'Home:Profile' %}">Profile</a> </h5>
                    <h4 class="w-100 mt-5 mb-3">Give Information</h4>

                    <form class="donation-form" action="{% url 'chatbot:faq' %}" method="post">

                        {% csrf_token %}


                        <div id ="form-fields"  class="billing-information  d-flex flex-wrap justify-content-between align-items-center">

                            <div class="form-field" >

                            </div>

<!--                            <input type="text" placeholder="Question 1" name="qs1">-->
<!--                            <input type="text" placeholder="Answer 1" name="ans1">-->

<!--                            <input type="text" placeholder="Question 2" name="qs2">-->
<!--                            <input type="text" placeholder="Answer 2" name="ans2">-->

<!--                            <input type="text" placeholder="Question 3" name="qs3">-->
<!--                            <input type="text" placeholder="Answer 3" name="ans3">-->

<!--                            <input type="text" placeholder="Question 4" name="qs4">-->
<!--                            <input type="text" placeholder="Answer 4" name="ans4">-->

<!--                            <input type="text" placeholder="Question 5" name="qs5">-->
<!--                            <input type="text" placeholder="Answer 5" name="ans5">-->
                        </div>
<!--                        <button id ="add-field" class="btn gradient-bg mt-5">Add More</button>-->
                        <input class="btn gradient-bg mt-5" type="submit" value="Get Bot">
                    </form>
                    <button id ="add-field" class="btn gradient-bg mt-5">Add More</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        $(document).ready(function() {
            var formFieldsContainer = $('#form-fields');
            var addFieldButton = $('#add-field');

            $(addFieldButton).click(function() {
                var fieldHTML = '<div class="form-field">' +
                                    '<input type="text" placeholder = "Question' +($('.form-field').length + 1) + '"  name="qs' + ($('.form-field').length + 1) + '">' + " "+
                                    '<input type="text" placeholder = "Answer' +($('.form-field').length + 1) + '"  name="ans' + ($('.form-field').length + 1) + '">'+
                                '</div>';

                $(formFieldsContainer).append(fieldHTML);
            });
        });
    </script>

{% endblock %}

templates/chatbot/chat_msg.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}


<head>

    <style>

.containerr {
  border: 2px solid #dedede;
  background-color: white;
  border-radius: 5px;
  padding: 10px;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 100px;
  width : 1000px;
}

.containerr_you {
  border: 2px solid #dedede;
  background-color: white;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 100px;
  width : 1000px;
  height : 70px;
}

.darker {
  border-color: #ccc;
  background-color: orange;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 100px;
  width : 1000px;
}

.containerr::after {
  content: "";
  clear: both;
  display: table;
}

.containerr img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.containerr img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #3C0C0C;
}

.time-left {
  float: left;
  color: #3C0C0C;
}
</style>
</head>

<br><br>

<h4 style="text-align:center">Chat Messages V1.0.0</h4>

<div class="containerr_you">
  <h6>{{msg1}}</h6>
            <span class="time-left">You</span>

</div>

<div class="containerr darker">
  <h6 class="time-right">{{msg}}</h6><br>
    <span class="time-right">From Bot </span>

</div>

<div class="containerr">
<form class="contact-form" method="post" >
    {% csrf_token %}

        <input type="text" name="msg">

    <span>
    <input class="btn gradient-bg"  type="submit" value="Send">
        </span>

</form>
    </div>








{% endblock %}

templates/chatbot/code.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}

<!--<h4 style="color : purple; padding : 10px;">This is your API :  aimaker/api/ChatAPI/{{code}} </h4>-->
<div style="text-align:center">
<a style="color : purple; padding : 10px; font-size:20px;" href="{% url 'payment:paymentt' %}"><img src="{% static 'images/point.png' %}">Get Api</a>
<br><br>
<h6><i style="color : purple; padding : 10px;">You can check or test your bot here :</i> </h6>
<a style="color : purple; padding : 10px;" href="{% url 'chatbot:chat' action_id=code %}"><img src="{% static 'images/point.png' %}">Click Here</a>
</div>
<br><br>
{% endblock %}

templates/chatbot/code_api.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
<br><br>
<div style="text-align:center">
<h4 style="color : purple; padding : 10px;"><img src="{% static 'images/point.png' %}">This is your API :  aimaker/api/ChatAPI/{{code}} </h4>
<br><br>
<h6><i style="color : purple; padding : 10px;">You can check or test your bot here :</i> </h6>
<a style="color : purple; padding : 10px;" href="{% url 'chatbot:chat' action_id=code %}"><img src="{% static 'images/point.png' %}">Click Here</a>
</div>
<br><br>
{% endblock %}

templates/chatbot/test.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dynamic Form</title>
    <style>
        body {
            margin: 0;
            overflow: hidden;
        }

        #canvas-container {
            width: 100%;
            height: 100%;
        }

        #form-container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
        }

        .form-field {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div id="canvas-container"></div>

    <div id="form-container">
        <h2>Add Data</h2>
        <form id="dynamic-form" method="post">
            {% csrf_token %}
            <div id="form-fields">
                <div class="form-field">

                </div>

            </div>
            <button type="button" id="add-field">Add</button>
            <button type="submit">Submit</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        $(document).ready(function() {
            var formFieldsContainer = $('#form-fields');
            var addFieldButton = $('#add-field');

            $(addFieldButton).click(function() {
                var fieldHTML = '<div class="form-field">' +
                                     '<label>qs ' + ($('.form-field').length + 1) + ':</label>' +
                                    '<input type="text" name="qs' + ($('.form-field').length + 1) + '">' + " "+
                                    '<label>ans ' + ($('.form-field').length + 1) + ':</label>' +
                                    '<input type="text" name="ans' + ($('.form-field').length + 1) + '">'+
                                '</div>';

                $(formFieldsContainer).append(fieldHTML);
            });
        });
    </script>
</body>
</html>

templates/chatbot/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}

    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1></h1>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .page-header -->

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="donation-form-wrap">
                    <h2>Hi {{name}}!</h2>
                    <br>
                    <h5><i style="color:blue">Note: </i> This Chatbot will create based on your "Company Type". You can change your "Company Type" from your <a style="text-decoration: none; color:blue;" href="{% url 'Home:Profile' %}">Profile</a> </h5>
                    <h4 class="mt-5">Create Your Own Chatbot</h4>

                    <form class="donation-form" action="{% url 'chatbot:update' pk=user_api %}" method="post">

                        {% csrf_token %}


                        <div id = "form-fields" class="billing-information  d-flex flex-wrap justify-content-between align-items-center">
                            <h4 class="w-100 mt-5 mb-3">Give Information</h4>


                            <div class = "form-field">

                                {% for i in user %}

                            <input type="text" value="{{i.0}}" name="qs{{i}}" >
                            <input type="text" value="{{i.1}}" name="ans{{i}}" >

                            {% endfor %}

                            </div>

<!--                            <input type="text" value="{{user.qs2}}" name="qs2">-->
<!--                            <input type="text" value="{{user.ans2}}" name="ans2">-->

<!--                            <input type="text" value="{{user.qs3}}" name="qs3">-->
<!--                            <input type="text" value="{{user.ans3}}" name="ans3">-->

<!--                            <input type="text" value="{{user.qs4}}" name="qs4">-->
<!--                            <input type="text" value="{{user.ans4}}" name="ans4">-->

<!--                            <input type="text" value="{{user.qs5}}" name="qs5">-->
<!--                            <input type="text" value="{{user.ans5}}" name="ans5">-->
                        </div>
                        <span>
                            <input class="btn gradient-bg mt-5" type="submit" value="Update Bot">
                            <a href="{% url 'chatbot:delete' pk=user_api %}" class="btn gradient-bg mt-5">Delete bot</a>
                        </span>
                    </form>
                    <button id ="add-field" class="btn gradient-bg mt-5">Add More</button>
                </div>
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        $(document).ready(function() {
            var formFieldsContainer = $('#form-fields');
            var addFieldButton = $('#add-field');

            $(addFieldButton).click(function() {
                var fieldHTML = '<div class="form-field">' +
                                    '<input type="text" placeholder = "Question' +($('.form-field').length + 1) + '"  name="qs' + ($('.form-field').length + 1) + '">' + " "+
                                    '<input type="text" placeholder = "Answer' +($('.form-field').length + 1) + '"  name="ans' + ($('.form-field').length + 1) + '">'+
                                '</div>';

                $(formFieldsContainer).append(fieldHTML);
            });
        });
    </script>

{% endblock %}