Api/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('ChatAPI/<str:id>', ChatAPI.as_view(),name="ChatAPI"),

]

GenQR/urls.py
from django.urls import path
from .views import *


urlpatterns=[
    path('qr', Generate_QR, name='Generate_QR'),

]

Home/urls.py
from django.urls import path
from .views import *


urlpatterns=[
    path('', home2, name='home2'),
    path('home', home, name='home'),
    path('about', About, name='About'),
    path('test', test, name='test'),
    path('test_another', test_another, name='test_another'),

    path('Dashboard', Dashboard, name='Dashboard'),
    path('Login', Login, name='Login'),
    path('Logout', Logout, name='Logout'),
    path('send_simple_message', send_simple_message, name='send_simple_message'),
    path('verify/<action_id>', verify, name='verify'),
    path('Recover/<action_id>', Recover, name='Recover'),
    path('Services', Services, name='Services'),
    path('Registration', Registration, name='Registration'),
    path('Profile', Profile, name='Profile'),
    path('Profile_Pic_Edit/<action_id>', Profile_Pic_Edit, name='Profile_Pic_Edit'),
    path('Profile_Info_Edit/<action_id>', Profile_Info_Edit, name='Profile_Info_Edit'),

]

ImgtoPdf/urls.py
from django.urls import path
from .views import *


urlpatterns=[
    path('convert', imgtopdfconv, name='imgtopdfconv'),
    # path('download', downloadpdf, name='downloadpdf'),

]

chatbot/urls.py
from django.urls import path
from .views import *


urlpatterns=[

    path('faq', faq, name='faq'),
    path('test', Test, name='Test'),
    path('chat/<action_id>', chat,name='chat'),
    path('update/<pk>', update,name='update'),
    path('delete/<pk>', delete,name='delete'),

]

myuniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Home.urls', 'Home'), namespace='Home')),
    path('Admin/', include(('Admin.urls', 'Admin'), namespace='Admin')),
    path('roomchat/', include(('roomchat.urls', 'roomchat'), namespace='roomchat')),
    path('chatbot/', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
    path('generate/', include(('GenQR.urls', 'GenQR'), namespace='GenQR')),
    path('api/', include(('Api.urls', 'Api'), namespace='Api')),
    path('imgtopdf/', include(('ImgtoPdf.urls', 'ImgtoPdf'), namespace='ImgtoPdf')),
    path('getpayment/', include(('payment.urls', 'payment'), namespace='payment')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roomchat/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # path('',v.home, name = 'home'),
    path('<str:room>/', room, name='room'),
    path('checkview', checkview, name='checkview'),
    path('send', send, name='send'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),


]

Home/models.py
from django.db import models

# Create your models here.

class Registration(models.Model):
    ID = models.AutoField(primary_key = True)
    Name = models.CharField(blank=True, max_length=500, null=True)
    Phone = models.CharField(blank=True, max_length=500, null=True,unique=True)
    Email = models.CharField(blank=True, max_length=500, null=True, unique=True)
    Gender = models.CharField(blank=True, max_length=500, null=True)
    Password = models.CharField(blank=True, max_length=500, null=True)
    pro_pic = models.CharField(blank=True, max_length=500, null=True)
    last_login = models.CharField(blank=True, max_length=500, null=True)
    OTP = models.CharField(blank=True, max_length=500, null=True)
    type = models.CharField(blank=True, max_length=1000, null=True)

Home/views.py
import hashlib

import requests
from django.shortcuts import render,redirect,HttpResponse
from .models import Registration as reg
from PIL import Image
from django.core.files import File
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_protect
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from io import BytesIO
import os
import random
import smtplib
import ssl
from email.message import EmailMessage
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import auth

def test(request):
    return render(request,'Home/test_chat.html')
def test_another(request):
    return render(request,'Home/test_chat2.html')

def About(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    return render(request,'Home/about.html')

# Create your views here.
def image_compress_save(image, img_name,f_name):
    im = Image.open(image)  # or self.files['image'] in your form
    # destroy color pew pew
    im = im.convert('RGB')
    im_io = BytesIO()
    im.save(im_io, 'JPEG', quality=60)
    compressed_image = File(im_io, name=img_name)
    print(settings.STATIC_URL)
    print(settings.STATIC_ROOT)
    print(settings.STATICFILES_DIRS[0])
    FileSystemStorage(location=os.path.join(settings.STATICFILES_DIRS[0], 'UPLOAD', 'NewUser',f_name)).save(img_name,
                                                                                                    compressed_image)
def listToString(s):

    str1 = ""

    for ele in s:
        str1 += ele

    return str1

def encode(pk):
    j = random.randint(1001, 9999)
    code = 'Chatbotapi' + str(j) + str(pk)
    return code

def decode(pk):
    code = list(pk)
    pk = code[14:]
    return listToString(pk)

def send_simple_message(request):

    if request.method == 'GET':

        return render(request,'Home/forgot_password.html')


    if request.method == 'POST':

        data = request.POST

        if reg.objects.filter(Email = data['email']):

            otp = random.randint(1000 , 9999)
            user_obj = reg.objects.get(Email = data['email'])
            user_obj.OTP = otp
            user_obj.save()


            # Define email sender and receiver
            email_sender = 'ayonssolution@gmail.com'
            email_password = 'sexbmaxiqtzhyylp'
            email_receiver = data['email']

            # Set the subject and body of the email
            subject = 'Recover Password'
            body = """
                This is your OTP {}
            """.format(otp)

            em = EmailMessage()
            em['From'] = email_sender
            em['To'] = email_receiver
            em['Subject'] = subject
            em.set_content(body)

            # Add SSL (layer of security)
            context = ssl.create_default_context()

            # Log in and send the email
            with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
                smtp.login(email_sender, email_password)
                smtp.sendmail(email_sender, email_receiver, em.as_string())

            return redirect('Home:verify',user_obj.ID)
        else:
            return HttpResponse('not ok')


def verify(request,action_id):

    if request.method == 'GET':

        user = reg.objects.get(ID = action_id)
        context = {
            'user' : user
        }
        return render(request,'Home/verify.html',context)

    if request.method == 'POST':

        data = request.POST

        user = reg.objects.get(ID=action_id)

        if data['verify'] == user.OTP:

            # return HttpResponse('ok')
            return redirect('Home:Recover',user.ID)
        else:
            context = {
                'msg' : 'wrong otp',
                'user': user
            }
            return render(request, 'Home/verify.html',context)


def Recover(request,action_id):

    if request.method == 'GET':
        user = reg.objects.get(ID=action_id)
        context = {
            'user': user
        }
        return render(request, 'Home/recover.html', context)

    if request.method == 'POST':

        data = request.POST

        user = reg.objects.get(ID=action_id)

        if data['pass1'] == data['pass2']:
            password = hashlib.md5(data['pass1'].encode('utf-8')).hexdigest()
            user.Password = password
            user.save()

            return redirect('Home:Login')
        else:
            context = {
                'msg': 'your password does not matched',
                'user': user
            }
            return render(request, 'Home/recover.html', context)

def home(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    return render(request,'Home/index.html')

def home2(request):
    return render(request,'Home/index2.html')

def Dashboard(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    return render(request,'Home/index.html')


def Services(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    return render(request,'Home/services.html')



def Profile(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    try:
        id = request.session['UserID']

        print(id)


        user =  reg.objects.get(ID=id)

        print(user.Name)
        context= {
            'user' : user
        }
        return render(request,'Home/profile.html',context)
    except:
        return redirect('Home:Login')



def Profile_Pic_Edit(request,action_id):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')


    user = reg.objects.get(ID=action_id)

    if request.method == 'GET':

        context= {
            'user' : user
        }
        return render(request,'Home/profile_pic_edit.html',context)

    if request.method == 'POST':

        try:
            os.remove('static/UPLOAD/NewUser/{}/{}'.format(str(action_id),user.pro_pic))
        except:
            pass

        name = user.Name

        title_name = name.replace(' ', '_')
        img_new_name = title_name + '_new' + '.jpg'
        image_compress_save(request.FILES['picture'], img_new_name,str(action_id))

        user.pro_pic = img_new_name
        user.save()


        return redirect('Home:Profile')


def Profile_Info_Edit(request,action_id):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    user = reg.objects.get(ID=action_id)

    if request.method == 'GET':

        context= {
            'user' : user
        }
        return render(request,'Home/profile_info_edit.html',context)

    if request.method == 'POST':

        data = request.POST

        password = hashlib.md5(data['passw'].encode('utf-8')).hexdigest()


        user.Name= data['name']
        user.Email= data['email']
        user.Phone = data['phone']
        user.Gender = data['gender']
        user.type = data['type']
        user.Password = password
        user.save()


        return redirect('Home:Profile')




@csrf_protect
def Login(request):

    if request.method == 'GET':
        return render(request, 'Home/login.html')

    if request.method == 'POST':
        # Login user
        data = request.POST
        email = data['email']

        password = hashlib.md5(data['passw'].encode('utf-8')).hexdigest()
        exists = reg.objects.filter(Email=email).exists()

        if not exists:
            context = {
                'msg': "Wrong Email"
            }

            return render(request, 'Home/login.html', context)

            # show message ('This Member does not exist')
            # return redirect('Home:Login')

        user = reg.objects.get(Email=email)
        if user.Password != password:
            # show message ('Wrong Password. Please Check Again')
            # return redirect('Home:Login')

            context = {
                'msg' : "Wrong Password"
            }

            return render(request,'Home/login.html',context)
        else:

            # Login Successfull

            request.session['VisitorStatus'] = 'user'
            request.session["UserID"] = user.ID
            request.session["UserName"] = user.Name

            user.last_login = datetime.now()
            user.save()

            idd = user.ID
            idd = encode(idd)

            return redirect('Home:Dashboard')


@csrf_protect
def Registration(request):

    if request.method == 'GET':
        return render(request,'Home/reg.html')

    if request.method == 'POST':
        # Register user
        data = request.POST

        name = data['name']
        email = data['email']
        phone = data['phone']
        gender = data['gender']
        passw = data['passw']
        repassw = data['repassw']
        chatbot_type = data['typee']



        if reg.objects.filter(Email=email).exists():
            # show flash message later

            context = {
                'msg1' : "This Email Already Exist"
            }

            return render(request,'Home/reg.html',context)

        elif reg.objects.filter(Phone=phone).exists():
            # show flash message later
            context = {
                'msg2' : "This Phone Number Already Exist"
            }

            return render(request,'Home/reg.html',context)

        elif passw == repassw:
            password = hashlib.md5(passw.encode('utf-8')).hexdigest()

            title_name =data['name'].replace(' ', '_')
            img_new_name = title_name+'.jpg'

templates/Home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} {% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- ElegantFonts CSS -->
    <link rel="stylesheet" href="{% static 'css/elegant-fonts.css' %}">

    <!-- themify-icons CSS -->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
   input {
  border-radius: 25px;
}
    </style>
</head>
<body>

    <header class="site-header">
        <div class="top-header-bar">
            <div class="container">
                <div class="row flex-wrap justify-content-center justify-content-lg-between align-items-lg-center">
                    <div class="col-12 col-lg-8 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                        <div class="header-bar-email">
                            MAIL: <a href="#">ayonssolution@gmail.com</a>
                        </div><!-- .header-bar-email -->

                        <div class="header-bar-text">
                            <p>PHONE: <span>+8801819468469 /+0181876544567 </span></p>
                        </div><!-- .header-bar-text -->
                    </div><!-- .col -->

                    <div class="col-12 col-lg-4 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                        <div class="donate-btn">
                            <a href="#">Join Us Now</a>
                        </div><!-- .donate-btn -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .top-header-bar -->
        <div class="nav-bar">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                        <div class="site-branding d-flex align-items-center">
                           <a class="d-block" href="index.html" rel="home"><img class="d-block" src="{% static 'images/Capture2.png' %}" height="50px;" width="200px;" alt="logo"></a>
                        </div><!-- .site-branding -->

                        <nav class="site-navigation d-flex justify-content-end align-items-center">
                            <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                                <li class="current-menu-item"><a href="/Dashboard">Home</a></li>
                                <li><a href="{% url 'Home:About' %}">About us</a></li>
                                <li><a href="{% url 'Home:Services' %}">Services</a></li>
                                <li><a href="{% url 'Home:Registration' %}">Register</a></li>

                            </ul>
                        </nav><!-- .site-navigation -->

                        <div class="hamburger-menu d-lg-none">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div><!-- .hamburger-menu -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .nav-bar -->
    </header><!-- .site-header -->

<!--    <div class="page-header">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-12">-->
<!--                    <h1>Log In</h1>-->
<!--                </div>&lt;!&ndash; .col &ndash;&gt;-->
<!--            </div>&lt;!&ndash; .row &ndash;&gt;-->
<!--        </div>&lt;!&ndash; .container &ndash;&gt;-->
<!--    </div>&lt;!&ndash; .page-header &ndash;&gt;-->

    <div>
    <div class="contact-page-wrap">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <form class="contact-form" method="post" action="{% url 'Home:Login' %}" enctype="multipart/form-data" style="background-image: url('static/images/myback.jpg');">
                        {% csrf_token %}
                        <h2 style="text-align:center; color:white">Login</h2>
                        <input type="email" placeholder="email" name="email" required>
                        <input style="width: 100%;
                                        padding: 12px 24px;
                                        margin-bottom: 18px;
                                        border: 1px solid #e0e0e0;
                                        font-size: 14px;
                                        line-height: 1;"
                               type="password" placeholder="Password" name="passw" required>
<!--                        <textarea rows="15" cols="6" placeholder="Messages"></textarea>-->
                        <h6 style="text-align:center; color:white">{{msg}}</h6>
                        <span>
                            <input class="btn gradient-bg" type="submit" value="Login">
                        </span>
                    </form><!-- .contact-form -->
                    <br>
                    <h6>Don't have account ? Create an account now </h6> <a style="color:orange; text-decoration:none;" href="{% url 'Home:Registration' %}"><b>Registration</b></a>
                    <h6>Forgot Password?</h6> <a style="color:orange; text-decoration:none;" href="{% url 'Home:send_simple_message' %}"><b>Recover</b></a>

                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div>

<footer class="site-footer">
        <div class="footer-widgets">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="foot-about">
                            <h2><a class="foot-logo" href="#"><img src="{% static 'images/cover.png' %}" height="50px" width="200px" alt=""></a></h2>

                            <p>
                                Contact Ayon's Solution today to discuss how we can transform your business with our comprehensive IT solutions. Let us be your trusted partner on your journey to success in the digital world.
                            </p>

                            <ul class="d-flex flex-wrap align-items-center">
                                <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-behance"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div><!-- .foot-about -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                        <h2>Useful Links</h2>

                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </div><!-- .col -->

<!--                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">-->
<!--                        <div class="foot-latest-news">-->
<!--                            <h2>Latest News</h2>-->

<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <h3><a href="#">A new cause to help</a></h3>-->
<!--                                    <div class="posted-date">MArch 12, 2018</div>-->
<!--                                </li>-->

<!--                                <li>-->
<!--                                    <h3><a href="#">We love to help people</a></h3>-->
<!--                                    <div class="posted-date">MArch 12, 2018</div>-->
<!--                                </li>-->

<!--                                <li>-->
<!--                                    <h3><a href="#">The new ideas for helping</a></h3>-->
<!--                                    <div class="posted-date">MArch 12, 2018</div>-->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>&lt;!&ndash; .foot-latest-news &ndash;&gt;-->
<!--                    </div>&lt;!&ndash; .col &ndash;&gt;-->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                        <div class="foot-contact">
                            <h2>Contact</h2>

                            <ul>
                                <li><i class="fa fa-phone"></i><span>+88018198475647</span></li>
                                <li><i class="fa fa-envelope"></i><span>office@template.com</span></li>
                                <li><i class="fa fa-map-marker"></i><span>Main Road. no 45-46, b3, 56832, Mirpur 11, Dhaka</span></li>
                            </ul>
                        </div><!-- .foot-contact -->

                        <div class="subscribe-form">
                            <form class="d-flex flex-wrap align-items-center">
                                <input type="email" placeholder="Your email">
                                <input type="submit" value="send">
                            </form><!-- .flex -->
                        </div><!-- .search-widget -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-widgets -->

        <div class="footer-bar">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p class="m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Ayonssolution Limited <i class="fa fa-heart-o" aria-hidden="true"></i>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div><!-- .col-12 -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-bar -->
    </footer><!-- .site-footer -->

    <script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.collapsible.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/swiper.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/circle-progress.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.countTo.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.barfiller.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/custom.js' %}"></script>

{% block custom_js %}{% endblock %}


</body>
</html>

templates/Home/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}

    <style>
   input {
  border-radius: 25px;
}
    </style>

    <div class="featured-cause">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="cause-wrap d-flex flex-wrap justify-content-between">
                        <figure class="m-0">
                            <img style="border-radius: 50%; height:200px; width:250px;" src="{% static 'UPLOAD/NewUser/' %}{{user.ID}}/{{user.pro_pic}}" alt="{{user.Name}}"><br><br>
                        </figure>

                        <div class="cause-content-wrap">
                            <header class="entry-header d-flex flex-wrap align-items-center">
                                <h3 class="entry-title w-100 m-0">{{user.Name}}</h3>

                                <div class="cats-links">
                                    {{user.Email}}
                                </div><!-- .cats-links -->
                            </header><!-- .entry-header -->



                            <div class="entry-footer mt-5">
                                <a href="{% url 'Home:Profile_Pic_Edit' action_id=user.ID %}" class="btn gradient-bg mr-2">Change</a>
                            </div><!-- .entry-footer -->
                        </div><!-- .cause-content-wrap -->

                        <div class="fund-raised w-100">
                            <div class="featured-fund-raised-bar barfiller">
                                <div class="tipWrap">
                                    <span class="tip"></span>
                                </div><!-- .tipWrap -->

                                <span class="fill" data-percentage="100"></span>
                            </div><!-- .fund-raised-bar -->
                        </div><!-- .fund-raised -->
                    </div><!-- .cause-wrap -->
                </div><!-- .col -->


                <div class="col-12 col-lg-6" style="bottom: 45px">
<!--                    <div class="cause-wrap d-flex flex-wrap justify-content-between">-->
<!--                        <div class="cause-content-wrap">-->
                    <form class="contact-form" method="post" action="{% url 'Home:Registration' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h6><label>Name : </label></h6>
                        <input type="text" name="name" value="{{user.Name}}" readonly >
                        <h6><label>Phone : </label></h6>
                        <input type="text"  name="phone" value="{{user.Phone}}" readonly >
                        <h6><label>Email : </label></h6>
                        <input type="email"  name="email" value="{{user.Email}}" readonly >
                        <h6><label>Gender : </label></h6>
                        <input type="text"  name="gender" value="{{user.Gender}}" readonly >
                        <h6><label>Company Type : </label></h6>
                        <input type="text"  name="gender" value="{{user.type}}" readonly >
                        <h6><label>Password: </label></h6>
                        <input style="width: 100%;
                                        padding: 12px 24px;
                                        margin-bottom: 18px;
                                        border: 1px solid #e0e0e0;
                                        font-size: 14px;
                                        line-height: 1;"
                               type="password" name="passw" value="**********************" readonly>
<!--                        <textarea rows="15" cols="6" placeholder="Messages"></textarea>-->
                        <span>
                                <a href="{% url 'Home:Profile_Info_Edit' action_id=user.ID %}" class="btn gradient-bg mr-2">Update</a>
                        </span>
                    </form><!-- .contact-form -->

                </div><!-- .col -->

<!--                </div>-->
<!--                </div>-->


            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .featured-cause -->


  {% endblock %}