Api/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('ChatAPI/<str:id>', ChatAPI.as_view(),name="ChatAPI"),

]

GenQR/urls.py
from django.urls import path
from .views import *


urlpatterns=[
    path('qr', Generate_QR, name='Generate_QR'),

]

myuniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Home.urls', 'Home'), namespace='Home')),
    path('Admin/', include(('Admin.urls', 'Admin'), namespace='Admin')),
    path('roomchat/', include(('roomchat.urls', 'roomchat'), namespace='roomchat')),
    path('chatbot/', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
    path('generate/', include(('GenQR.urls', 'GenQR'), namespace='GenQR')),
    path('api/', include(('Api.urls', 'Api'), namespace='Api')),
    path('imgtopdf/', include(('ImgtoPdf.urls', 'ImgtoPdf'), namespace='ImgtoPdf')),
    path('getpayment/', include(('payment.urls', 'payment'), namespace='payment')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/QR/download_qr.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
<br><br>
<center>
   <h4>Download Your QR</h4>
    <button class="btn gradient-bg">
            <a href="{% static 'UPLOAD/qrimg/' %}{{UserName}}.png" download>Download</a>

    </button>

</center>
<br><br>

{% endblock %}

templates/QR/generate_qr.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
<br><br>
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>Create Your Own QR</h1>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .page-header -->

    <div class="contact-page-wrap">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <form class="contact-form" method="post" action="{% url 'GenQR:Generate_QR' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea rows="8" type="text" placeholder="Type Here" name="value">

                        </textarea>
                        <span>
                            <input class="btn gradient-bg" type="submit" value="Create QR">
                        </span>
                    </form><!-- .contact-form -->
                </div><!-- .col -->
                <div class="col-14 col-lg-6">
                    <h6>Example of creating QR code</h6>
                    <img src="{% static 'images/alex.png' %}" height="400px" width="500px">
                </div>
            </div><!-- .row -->
        </div><!-- .container -->
    </div>

  {% endblock %}