Api/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('ChatAPI/<str:id>', ChatAPI.as_view(),name="ChatAPI"),

]

myuniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Home.urls', 'Home'), namespace='Home')),
    path('Admin/', include(('Admin.urls', 'Admin'), namespace='Admin')),
    path('roomchat/', include(('roomchat.urls', 'roomchat'), namespace='roomchat')),
    path('chatbot/', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
    path('generate/', include(('GenQR.urls', 'GenQR'), namespace='GenQR')),
    path('api/', include(('Api.urls', 'Api'), namespace='Api')),
    path('imgtopdf/', include(('ImgtoPdf.urls', 'ImgtoPdf'), namespace='ImgtoPdf')),
    path('getpayment/', include(('payment.urls', 'payment'), namespace='payment')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import *


urlpatterns=[

    path('pay', getapi_withpay, name='getapi_withpay'),
    path('payadvance', getapi_advance, name='getapi_advance'),
    path('paypro', getapi_pro, name='getapi_pro'),
    path('trial', getapi_trial, name='getapi_trial'),
    path('paymentt', paymentt, name='paymentt'),
    path('ssl', ssl, name='ssl'),
    path('success', success, name='success'),
    path('fail', fail, name='fail'),
    path('get_Api', get_Api, name='get_Api'),

]

payment/models.py
from django.db import models

# Create your models here.


class payment_info(models.Model):
    buyer_id  = models.CharField(blank=True, max_length=500, null=True)
    buyer_name  = models.CharField(blank=True, max_length=500, null=True)
    CardNumber  = models.CharField(blank=True, max_length=500, null=True)
    CardName  = models.CharField(blank=True, max_length=500, null=True)
    ExpiryDate = models.CharField(blank=True, max_length=20, null=True)
    amount = models.CharField(blank=True, max_length=500, null=True)
    buy_date = models.DateField(blank=True, max_length=50, null=True)
    Status = models.CharField(blank=True, max_length=50, null=True)

payment/views.py
import datetime

from django.shortcuts import render,HttpResponseRedirect,redirect
from django.views.decorators.csrf import csrf_exempt

from .models import *
from Home.views import encode, decode
# Create your views here.
from chatbot.models import Trial
from datetime import datetime, timedelta
from .check import gateway


# def success(request):

def getapi_withpay(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    try :
        user = payment_info.objects.get(buyer_id=request.session['UserID'])

        if user.Status == 'ok':
            code = encode(request.session['UserID'])
            context = {
                'code': code
            }
            return render(request, 'chatbot/code_api.html', context)

    except:

        if request.method == 'GET':
            return render(request,'payment/payment_plan.html')


        if request.method == 'POST':

            data =  request.POST
            # user = payment_info.objects.get(buyer_id = request.session['UserID'])

            if data['amount'] == '500.0' and len(data['cardNumber']) == 8:

                date = datetime.datetime.now()

                payment_info.objects.create(Status = 'ok',CardNumber = data['cardNumber'],CardName = data['cardName'],ExpiryDate = data['expiryDate'],buyer_name = request.session['UserName'] , buyer_id = request.session['UserID']  , amount = data['amount'] , buy_date = date)

                code = encode(request.session['UserID'])
                context = {
                    'code': code
                }
                return render(request,'chatbot/code_api.html',context)

            else:
                context = {
                    'msg' : 'Card is not valid'
                }
                return render(request, 'payment/get_bill_info.html',context)

def getapi_trial(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    if request.method == 'POST':

        try:
            Trial.objects.create(Idd = request.session['UserID'],Status = 'on', datee=datetime.today().date())
            code = encode(request.session['UserID'])
            context = {
                'code': code
            }
            return render(request, 'chatbot/code_api.html', context)

        except:
            context ={
                'message_trial' : 'you already use trial mode'
            }
            return render(request, 'payment/payment_plan2.html',context)


def getapi_advance(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    try :
        user = payment_info.objects.get(buyer_id=request.session['UserID'])
        print(1)
        if user.Status == 'ok':
            code = encode(request.session['UserID'])
            context = {
                'code': code
            }
            return render(request, 'chatbot/code_api.html', context)

        else:
            if request.method == 'GET':
                print(2)

                if payment_info.objects.get(buyer_id=request.session['UserID']):
                    user = payment_info.objects.get(buyer_id=request.session['UserID'])
                    user.delete()

                return render(request, 'payment/get_bill_info.html')

            if request.method == 'POST':

                data = request.POST
                # user = payment_info.objects.get(buyer_id = request.session['UserID'])

                if data['amount'] == '1800.0' and len(data['cardNumber']) == 8:

                    date = datetime.today().now()

                    payment_info.objects.create(Status='ok', CardNumber=data['cardNumber'], CardName=data['cardName'],
                                                ExpiryDate=data['expiryDate'], buyer_name=request.session['UserName'],
                                                buyer_id=request.session['UserID'], amount=data['amount'],
                                                buy_date=date)

                    user = Trial.objects.get(Idd=request.session['UserID'])
                    user.Status = 'over'
                    user.save()

                    code = encode(request.session['UserID'])
                    context = {
                        'code': code
                    }
                    return render(request, 'chatbot/code_api.html', context)

                else:
                    context = {
                        'msg': 'Card is not valid'
                    }
                    return render(request, 'payment/get_bill_info.html', context)

    except:

        if request.method == 'GET':
            print(2)

            # if payment_info.objects.get(buyer_id = request.session['UserID']):
            #     user = payment_info.objects.get(buyer_id = request.session['UserID'])
            #     user.delete()

            return render(request,'payment/get_bill_info.html')


        if request.method == 'POST':

            data =  request.POST
            # user = payment_info.objects.get(buyer_id = request.session['UserID'])

            if data['amount'] == '1800.0' and len(data['cardNumber']) == 8:

                date = datetime.today().now()

                payment_info.objects.create(Status = 'ok',CardNumber = data['cardNumber'],CardName = data['cardName'],ExpiryDate = data['expiryDate'],buyer_name = request.session['UserName'] , buyer_id = request.session['UserID']  , amount = data['amount'] , buy_date = date)

                # user = Trial.objects.get(Idd=request.session['UserID'])
                # user.Status = 'over'
                # user.save()

                code = encode(request.session['UserID'])
                context = {
                    'code': code
                }
                return render(request,'chatbot/code_api.html',context)

            else:
                context = {
                    'msg' : 'Card is not valid'
                }
                return render(request, 'payment/get_bill_info.html',context)


def getapi_pro(request):
    if request.method == 'POST':
        return render(request, 'payment/get_bill_info.html')

def ssl(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    val = gateway('Ayonsolution','Ayonsolution@gmail.com')
    print(val['sessionkey'])

    return HttpResponseRedirect(val['GatewayPageURL'])


def paymentt(request):

    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    try:
        idd = request.session['UserID']
        user = Trial.objects.get(Idd=idd)

        if user.Status == 'over':
            return render(request, 'payment/payment_plan2.html')
        else:
            return render(request, 'payment/payment_plan2.html')


    except:

        return render(request, 'payment/payment_plan.html')


@csrf_exempt
def success(request):

    context = {
        'message': 'Payment Successful'
    }
    return render(request, 'payment/success.html', context)

def get_Api(request):
    if 'VisitorStatus' not in request.session or request.session['VisitorStatus'] != "user":
        return redirect('Home:Login')

    code = encode(request.session['UserID'])
    context = {
        'code': code
    }
    return render(request, 'chatbot/code_api.html', context)

@csrf_exempt
def fail(request):

    return redirect('payment:paymentt')

templates/payment/get_bill_info.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}

  <style>

    .containerr {
      max-width: 400px;
      margin: 0 auto;
      padding: 20px;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
      text-align: center;
    }

    .form-group {
      margin-bottom: 20px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    input[type="text"],
    input[type="email"],
    input[type="password"],
    select {
      width: 100%;
      padding: 10px;
      border-radius: 3px;
      border: 1px solid #ccc;
    }

    button {
      display: block;
      width: 100%;
      padding: 10px;
      background-color: #4CAF50;
      border: none;
      color: #fff;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
    }

    button:hover {
      background-color: #45a049;
    }
  </style>
<br><br>
  <div class="containerr">
    <h2>Payment Gateway</h2>
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <h4>{{msg}}</h4>
        <label for="cardNumber">Card Number</label>
        <input type="text" id="cardNumber" name="cardNumber" placeholder="Enter card number">
      </div>
      <div class="form-group">
        <label for="cardName">Cardholder Name</label>
        <input type="text" id="cardName" name="cardName" placeholder="Enter cardholder name">
      </div>
      <div class="form-group">
        <label for="expiryDate">Expiry Date</label>
        <input type="text" id="expiryDate" name="expiryDate" placeholder="MM/YY">
      </div>
      <div class="form-group">
        <label for="amount">Amount</label>
        <input type="text" id="amount" name="amount" value="1800.0" readonly>
      </div>
      <button type="submit">Pay Now</button>
    </form>
  </div>


{% endblock %}

templates/payment/payment_plan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
  <style>

.container_pay {
  display: flex;
  justify-content: space-around;
  max-width: 800px;
  margin: 50px auto;
}

.card {
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  padding: 20px;
  text-align: center;
  width: 30%;
}

h2 {
  color: Black;
}

p {
  color: #444;
}

.button_pay {
  background-color: orange;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  margin-top: 20px;
  cursor: pointer;
}

  </style>

  <div class="container_pay">
    <form method="post" action="{% url 'payment:getapi_trial' %}" enctype="multipart/form-data" class="card">
      {% csrf_token %}
    <div>
      <h3>Basic</h3>
      <p>15 Days Trial</p>
      <button class="button_pay">Try it!</button>
    </div>
    </form>

    <form method="post" enctype="multipart/form-data" class="card">
      {% csrf_token %}
    <div>
      <h3>Advance</h3>
      <p>1800 BDT/ Four Month</p>
      <button  type="submit" class="button_pay"><a style="text-decoration:none; color:white;" href="{% url 'payment:getapi_advance' %}">Let's Go</a></button>
    </div>
    </form>

<!--    <form method="post" action="{% url 'payment:getapi_pro' %}" enctype="multipart/form-data" class="card">-->
<!--      {% csrf_token %}-->
<!--    <div>-->
<!--      <h2>Pro</h2>-->
<!--      <p>5000 BDT/Year</p>-->
<!--      <button class="button_pay">Let's Go</button>-->
<!--    </div>-->
<!--    </form>-->
  </div>

{% endblock %}

templates/payment/payment_plan2.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
  <style>

.container_pay {
  display: flex;
  justify-content: space-around;
  max-width: 800px;
  margin: 50px auto;
}

.card {
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  padding: 20px;
  text-align: center;
  width: 30%;
}

h2 {
  color: Black;
}

p {
  color: #444;
}

.button_pay {
  background-color: orange;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  margin-top: 20px;
  cursor: pointer;
}

  </style>

  <div class="container_pay">
    <h4>{{message_trial}}</h4>
    <form method="post" enctype="multipart/form-data" class="card">
      {% csrf_token %}
    <div>
      <h2>Advance</h2>
      <p>1800 BDT/ Four Month</p>
      <button type="submit" class="button_pay"><a style="text-decoration:none; color:white;" href="{% url 'payment:getapi_advance' %}">Let's Go</a></button>
    </div>
    </form>

<!--    <form method="post" action="{% url 'payment:ssl' %}" enctype="multipart/form-data" class="card">-->
<!--      {% csrf_token %}-->
<!--    <div>-->
<!--      <h2>Pro</h2>-->
<!--      <p>5000 BDT/Year</p>-->
<!--      <button class="button_pay">Let's Go</button>-->
<!--    </div>-->
<!--    </form>-->
  </div>

{% endblock %}

templates/payment/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cloud{% endblock %}


{% block body %}
  <style>

.container_pay {
  display: flex;
  justify-content: space-around;
  max-width: 800px;
  margin: 50px auto;
}

.card {
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  padding: 20px;
  text-align: center;
  width: 30%;
}

h2 {
  color: Black;
}

p {
  color: #444;
}

.button_pay {
  background-color: orange;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  margin-top: 20px;
  cursor: pointer;
}

  </style>

<div style="text-align:center">
  <div class="container_pay">
    <h4>{{message}}</h4>
  </div>
<a style="color : purple; padding : 10px; font-size:20px;" href="{% url 'payment:get_Api' %}"><img src="{% static 'images/point.png' %}">Get Api</a>
  <br><br>
</div>

{% endblock %}